services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
      - ./common:/common
    environment:
      - PYTHONPATH=/app:/common
    depends_on:
      db:
        condition: service_healthy

  image-worker:
    build:
      context: ./image-worker
      dockerfile: Dockerfile
    env_file:
      - ./image-worker/.env
    volumes:
      - ./image-worker:/app
      - ./common:/common
      - ./image-worker/uploads:/app/uploads
    environment:
      - PYTHONPATH=/app:/common
    depends_on:
      db:
        condition: service_healthy
    command: watchfiles --filter python "python -u main.py"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    env_file:
      - ./frontend/.env.development

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=photo_palettes
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  frontend_node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./frontend/node_modules
