export const MODAL_ID = {
  ANON_PALETTE_CREATION_MODAL: 'ANON_PALETTE_CREATION_MODAL',
  CONFIRMATION_MODAL: 'CONFIRMATION_MODAL',
  SHARE_TO_SOCIALS_MODAL: 'SHARE_TO_SOCIALS_MODAL',
  LIGHTBOX_MODAL: 'LIGHTBOX_MODAL',
  CONFIRM_ACCOUNT_DELETION_MODAL: 'CONFIRM_ACCOUNT_DELETION_MODAL',
  WHATS_NEW_MODAL: 'WHATS_NEW_MODAL',
} as const
