export const MODAL_ID = {
  ANON_PALETTE_CREATION_MODAL: 'ANON_PALETTE_CREATION_MODAL',
  CONFIRMATION_MODAL: 'CONFIRMATION_MODAL',
  SHARE_TO_SOCIALS: 'SHARE_TO_SOCIALS',
  LIGHTBOX_MODAL: 'LIGHTBOX_MODAL',
} as const
