"""user-and-color-palettes

Revision ID: 18e4248220b4
Revises: 73a7c71ec391
Create Date: 2025-04-25 20:25:06.382322

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.types import UserDefinedType

from alembic import op


class Cube(UserDefinedType):
    def get_col_spec(self, **kw):
        return "CUBE"


# revision identifiers, used by Alembic.
revision: str = "18e4248220b4"
down_revision: Union[str, None] = "73a7c71ec391"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("auth_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("permission_level", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("auth_id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "palettes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("app_user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("photo_details", sa.String(), nullable=False),
        sa.Column("moderation_status", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["app_user_id"],
            ["app_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "palette_colors",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("palette_id", sa.Uuid(), nullable=False),
        sa.Column("hex", sa.String(), nullable=False),
        sa.Column("r", sa.Integer(), nullable=False),
        sa.Column("g", sa.Integer(), nullable=False),
        sa.Column("b", sa.Integer(), nullable=False),
        sa.Column("rgb_cube", Cube(), nullable=False),
        sa.ForeignKeyConstraint(
            ["palette_id"],
            ["palettes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("palette_colors")
    op.drop_table("palettes")
    op.drop_table("app_users")
    # ### end Alembic commands ###
