"""moderation

Revision ID: 20c04fea2bd3
Revises: c3fb796db818
Create Date: 2025-04-20 23:12:09.538294

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20c04fea2bd3"
down_revision: Union[str, None] = "c3fb796db818"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first
    op.add_column(
        "palettes", sa.Column("moderation_status", sa.Integer(), nullable=True)
    )
    op.add_column("users", sa.Column("permission_level", sa.Integer(), nullable=True))

    # Set default values for existing records
    op.execute("UPDATE palettes SET moderation_status = 0")  # PENDING
    op.execute("UPDATE users SET permission_level = 0")  # MEMBER

    # Now make the columns NOT NULL
    op.alter_column("palettes", "moderation_status", nullable=False)
    op.alter_column("users", "permission_level", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "permission_level")
    op.drop_column("palettes", "moderation_status")
    # ### end Alembic commands ###
