"""blurhash

Revision ID: 3027387b8dea
Revises: adda276a8959
Create Date: 2025-05-09 22:32:56.976088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3027387b8dea'
down_revision: Union[str, None] = 'adda276a8959'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('palettes', sa.Column('blurhash', sa.String(), nullable=False))
    op.add_column('palettes', sa.Column('aspect_ratio', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('palettes', 'aspect_ratio')
    op.drop_column('palettes', 'blurhash')
    # ### end Alembic commands ###
