"""hsl

Revision ID: 3eeade051a02
Revises: d26f0f7bdecc
Create Date: 2025-04-17 21:28:36.790788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3eeade051a02'
down_revision: Union[str, None] = 'd26f0f7bdecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('colors', sa.Column('hsl', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('colors', 'hsl')
    # ### end Alembic commands ###
