"""add_percent_loc_to_palette_color

Revision ID: a4d7b2f679f1
Revises: 1d3411ee21b2
Create Date: 2025-09-02 20:45:28.643890

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a4d7b2f679f1"
down_revision: str | None = "1d3411ee21b2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "palette_colors", sa.Column("percent_location", sa.ARRAY(sa.Float), nullable=True)
    )

    # 2. Backfill
    op.execute(
        "UPDATE palette_colors SET percent_location = ARRAY[0.0, 0.0] WHERE percent_location IS NULL"
    )

    # 3. Alter to NOT NULL
    op.alter_column("palette_colors", "percent_location", nullable=False)


# ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("palette_colors", "percent_location")
    # ### end Alembic commands ###
