"""og-img

Revision ID: adda276a8959
Revises: c097148903b5
Create Date: 2025-05-02 00:39:26.474235

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "adda276a8959"
down_revision: str | None = "c097148903b5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("palettes", sa.Column("og_photo_details", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("palettes", "og_photo_details")
    # ### end Alembic commands ###
