"""feature-requests

Revision ID: c097148903b5
Revises: 18e4248220b4
Create Date: 2025-04-30 16:16:14.434702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c097148903b5'
down_revision: Union[str, None] = '18e4248220b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feature_request_votes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('app_user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['app_user_id'], ['app_users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['feature_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feature_request_votes')
    op.drop_table('feature_requests')
    # ### end Alembic commands ###
