"""user-and-palette

Revision ID: c3fb796db818
Revises: 73a7c71ec391
Create Date: 2025-04-20 19:04:46.459064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.types import UserDefinedType

class Cube(UserDefinedType):
    def get_col_spec(self, **kw):
        return "CUBE"

# revision identifiers, used by Alembic.
revision: str = 'c3fb796db818'
down_revision: Union[str, None] = '73a7c71ec391'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('auth_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('palettes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('palette_colors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('palette_id', sa.String(), nullable=False),
    sa.Column('hex', sa.String(), nullable=False),
    sa.Column('r', sa.Integer(), nullable=False),
    sa.Column('g', sa.Integer(), nullable=False),
    sa.Column('b', sa.Integer(), nullable=False),
    sa.Column('rgb_cube', Cube(), nullable=False),
    sa.ForeignKeyConstraint(['palette_id'], ['palettes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('palette_colors')
    op.drop_table('palettes')
    op.drop_table('users')
    # ### end Alembic commands ###
