"""add hex

Revision ID: d26f0f7bdecc
Revises: 31ffbe858f54
Create Date: 2025-04-17 00:15:14.955891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd26f0f7bdecc'
down_revision: Union[str, None] = '31ffbe858f54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('colors', sa.Column('hex', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('colors', 'hex')
    # ### end Alembic commands ###
