"""add_cascade_deletion

Revision ID: dbe6566e9cb3
Revises: d3512b07dc52
Create Date: 2025-08-25 20:49:39.621650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbe6566e9cb3'
down_revision: Union[str, None] = 'd3512b07dc52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('feature_request_votes_request_id_fkey', 'feature_request_votes', type_='foreignkey')
    op.drop_constraint('feature_request_votes_app_user_id_fkey', 'feature_request_votes', type_='foreignkey')
    op.create_foreign_key(None, 'feature_request_votes', 'app_users', ['app_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'feature_request_votes', 'feature_requests', ['request_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('palette_colors_palette_id_fkey', 'palette_colors', type_='foreignkey')
    op.create_foreign_key(None, 'palette_colors', 'palettes', ['palette_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('palette_favorites_palette_id_fkey', 'palette_favorites', type_='foreignkey')
    op.drop_constraint('palette_favorites_app_user_id_fkey', 'palette_favorites', type_='foreignkey')
    op.create_foreign_key(None, 'palette_favorites', 'app_users', ['app_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'palette_favorites', 'palettes', ['palette_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('palettes_app_user_id_fkey', 'palettes', type_='foreignkey')
    op.create_foreign_key(None, 'palettes', 'app_users', ['app_user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'palettes', type_='foreignkey')
    op.create_foreign_key('palettes_app_user_id_fkey', 'palettes', 'app_users', ['app_user_id'], ['id'])
    op.drop_constraint(None, 'palette_favorites', type_='foreignkey')
    op.drop_constraint(None, 'palette_favorites', type_='foreignkey')
    op.create_foreign_key('palette_favorites_app_user_id_fkey', 'palette_favorites', 'app_users', ['app_user_id'], ['id'])
    op.create_foreign_key('palette_favorites_palette_id_fkey', 'palette_favorites', 'palettes', ['palette_id'], ['id'])
    op.drop_constraint(None, 'palette_colors', type_='foreignkey')
    op.create_foreign_key('palette_colors_palette_id_fkey', 'palette_colors', 'palettes', ['palette_id'], ['id'])
    op.drop_constraint(None, 'feature_request_votes', type_='foreignkey')
    op.drop_constraint(None, 'feature_request_votes', type_='foreignkey')
    op.create_foreign_key('feature_request_votes_app_user_id_fkey', 'feature_request_votes', 'app_users', ['app_user_id'], ['id'])
    op.create_foreign_key('feature_request_votes_request_id_fkey', 'feature_request_votes', 'feature_requests', ['request_id'], ['id'])
    # ### end Alembic commands ###
