"""add_color_name

Revision ID: 55369f1fb9fe
Revises: cd7f388ebe1d
Create Date: 2025-09-30 15:15:37.779360

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "55369f1fb9fe"
down_revision: Union[str, None] = "cd7f388ebe1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column("palette_colors", sa.Column("name", sa.String(), nullable=True))

    # Update all existing rows to have empty string
    op.execute("UPDATE palette_colors SET name = ''")

    # Now add the NOT NULL constraint
    op.alter_column("palette_colors", "name", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("palette_colors", "name")
    # ### end Alembic commands ###
