"""add_worker_table

Revision ID: cd7f388ebe1d
Revises: 435cd9019f86
Create Date: 2025-09-18 19:51:41.159098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd7f388ebe1d'
down_revision: Union[str, None] = '435cd9019f86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_actions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('palette_id', sa.Uuid(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('json_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['palette_id'], ['palettes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worker_actions')
    # ### end Alembic commands ###