"""add_favorites_table

Revision ID: d3512b07dc52
Revises: 3027387b8dea
Create Date: 2025-08-25 18:46:40.820670

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d3512b07dc52"
down_revision: str | None = "3027387b8dea"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "palette_favorites",
        sa.Column("app_user_id", sa.Uuid(), nullable=False),
        sa.Column("palette_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["app_user_id"],
            ["app_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["palette_id"],
            ["palettes.id"],
        ),
        sa.PrimaryKeyConstraint("app_user_id", "palette_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("palette_favorites")
    # ### end Alembic commands ###
